/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntitiesRouteImport } from './routes/entities'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as ImagesRouteImport } from './routes/images'
import { Route as InvestigationsRouteImport } from './routes/investigations'
import { Route as LiveRouteImport } from './routes/live'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as NewsRouteImport } from './routes/news'
import { Route as OsintRouteImport } from './routes/osint'
import { Route as SentimentRouteImport } from './routes/sentiment'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as VideosRouteImport } from './routes/videos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesRoute = EntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesRoute = ImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsRoute = InvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const OsintRoute = OsintRouteImport.update({
  id: '/osint',
  path: '/osint',
  getParentRoute: () => rootRouteImport,
} as any)
const SentimentRoute = SentimentRouteImport.update({
  id: '/sentiment',
  path: '/sentiment',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entities': typeof EntitiesRoute
  '/graph': typeof GraphRoute
  '/images': typeof ImagesRoute
  '/investigations': typeof InvestigationsRoute
  '/live': typeof LiveRoute
  '/network': typeof NetworkRoute
  '/news': typeof NewsRoute
  '/osint': typeof OsintRoute
  '/sentiment': typeof SentimentRoute
  '/settings': typeof SettingsRoute
  '/social': typeof SocialRoute
  '/subjects': typeof SubjectsRoute
  '/timeline': typeof TimelineRoute
  '/trends': typeof TrendsRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entities': typeof EntitiesRoute
  '/graph': typeof GraphRoute
  '/images': typeof ImagesRoute
  '/investigations': typeof InvestigationsRoute
  '/live': typeof LiveRoute
  '/network': typeof NetworkRoute
  '/news': typeof NewsRoute
  '/osint': typeof OsintRoute
  '/sentiment': typeof SentimentRoute
  '/settings': typeof SettingsRoute
  '/social': typeof SocialRoute
  '/subjects': typeof SubjectsRoute
  '/timeline': typeof TimelineRoute
  '/trends': typeof TrendsRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entities': typeof EntitiesRoute
  '/graph': typeof GraphRoute
  '/images': typeof ImagesRoute
  '/investigations': typeof InvestigationsRoute
  '/live': typeof LiveRoute
  '/network': typeof NetworkRoute
  '/news': typeof NewsRoute
  '/osint': typeof OsintRoute
  '/sentiment': typeof SentimentRoute
  '/settings': typeof SettingsRoute
  '/social': typeof SocialRoute
  '/subjects': typeof SubjectsRoute
  '/timeline': typeof TimelineRoute
  '/trends': typeof TrendsRoute
  '/videos': typeof VideosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entities'
    | '/graph'
    | '/images'
    | '/investigations'
    | '/live'
    | '/network'
    | '/news'
    | '/osint'
    | '/sentiment'
    | '/settings'
    | '/social'
    | '/subjects'
    | '/timeline'
    | '/trends'
    | '/videos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entities'
    | '/graph'
    | '/images'
    | '/investigations'
    | '/live'
    | '/network'
    | '/news'
    | '/osint'
    | '/sentiment'
    | '/settings'
    | '/social'
    | '/subjects'
    | '/timeline'
    | '/trends'
    | '/videos'
  id:
    | '__root__'
    | '/'
    | '/entities'
    | '/graph'
    | '/images'
    | '/investigations'
    | '/live'
    | '/network'
    | '/news'
    | '/osint'
    | '/sentiment'
    | '/settings'
    | '/social'
    | '/subjects'
    | '/timeline'
    | '/trends'
    | '/videos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntitiesRoute: typeof EntitiesRoute
  GraphRoute: typeof GraphRoute
  ImagesRoute: typeof ImagesRoute
  InvestigationsRoute: typeof InvestigationsRoute
  LiveRoute: typeof LiveRoute
  NetworkRoute: typeof NetworkRoute
  NewsRoute: typeof NewsRoute
  OsintRoute: typeof OsintRoute
  SentimentRoute: typeof SentimentRoute
  SettingsRoute: typeof SettingsRoute
  SocialRoute: typeof SocialRoute
  SubjectsRoute: typeof SubjectsRoute
  TimelineRoute: typeof TimelineRoute
  TrendsRoute: typeof TrendsRoute
  VideosRoute: typeof VideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images': {
      id: '/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations': {
      id: '/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof InvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/osint': {
      id: '/osint'
      path: '/osint'
      fullPath: '/osint'
      preLoaderRoute: typeof OsintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentiment': {
      id: '/sentiment'
      path: '/sentiment'
      fullPath: '/sentiment'
      preLoaderRoute: typeof SentimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntitiesRoute: EntitiesRoute,
  GraphRoute: GraphRoute,
  ImagesRoute: ImagesRoute,
  InvestigationsRoute: InvestigationsRoute,
  LiveRoute: LiveRoute,
  NetworkRoute: NetworkRoute,
  NewsRoute: NewsRoute,
  OsintRoute: OsintRoute,
  SentimentRoute: SentimentRoute,
  SettingsRoute: SettingsRoute,
  SocialRoute: SocialRoute,
  SubjectsRoute: SubjectsRoute,
  TimelineRoute: TimelineRoute,
  TrendsRoute: TrendsRoute,
  VideosRoute: VideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
